-- Create poetry table
create table poetry (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  dynasty text not null,
  style text not null,
  content text not null,
  popularity integer default 50,
  spread integer default 50,
  compulsory boolean default false,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable row level security
alter table poetry enable row level security;

-- Create policy for anonymous access
create policy "Anonymous access" on poetry
  for select using (true);
